# Generated by Django 4.1 on 2024-07-29 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stopwatch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stopwatch",
            name="user",
        ),
        migrations.AlterField(
            model_name="stopwatch",
            name="elapsed_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
